### ISSUE TITLE
Documentation for Adding a new entity

### ISSUE THREAD

**Issue by tacman** [tetranz/select2entity-bundle#150]
I'm following the instructions on how to add a new element, but am getting an error.  

```php
// In the form builder
                'allow_add' => [
                    'enabled' => true,
                    'new_tag_text' => ' (NEW)',
                    'new_tag_prefix' => '__',
                    'tag_separators' => '[";", "]'
                ],
```

Now instead of returning an array of objects of my class, it returns an array that includes strings.  The new_tag_text and prefix don't seem to be doing anything, at least not when I'm looking at what's submitted in the form.

I can intercept the text and create the new elements, but even when I do that, the $values array passed to the transform service includes the strings.  So it fails during the SQL, when it's trying to look up the objects by their id's, e.g.

```
FROM tag t0_ WHERE t0_.id IN (?, ?)' with params ["ABC IS A NEW ELEMENT", "3"]:
```

So I'm missing some critical step, where the new string is inserted into the database and gets an id.

Are there any examples?  I see there's a reference to a PrePersist Listener, but not sure how to implement that.

Thanks.

**Comment by tacman** [comment]
I've created an example of the problem I'm having adding a new entry to show the error I'm getting:

```
An exception occurred while executing 'SELECT c0_.id AS id_0, c0_.name AS name_1, c0_.alpha2 AS alpha2_2 FROM country c0_ WHERE c0_.id IN (?)' with params ["Elbona"]: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "Elbona"
```

![image](https://user-images.githubusercontent.com/619585/62058497-8f3dc180-b1ef-11e9-901b-4636c8c5a10c.png)

https://select2-demo.herokuapp.com/form/?formClass=App%5CForm%5CAddNewCountryFormType

Source code is also shown on that page.

So when a new element is added, the form contains an array that includes the new element as a _string_.  So how should this be handled?

Source code is at https://github.com/survos/select2entity-bundle-demo, takes only 30 seconds to clone and launch.

**Comment by tacman** [comment]
@tetranz Any chance you could look at this?  I'm sure it works, but I'm at a loss as to how to configure it.

**Comment by tetranz** [comment]
I'll try to take a look at this over the weekend.

**Comment by rosskea** [comment]
@tacman I had a play with this. Unfortunately I was not able to reproduce the problem.

Firstly, I couldn't install your repo because it requires PHP 7.3. I should probably upgrade my test VM to 7.3 but I don't have time for that right now.  It's something to do with ocramius/package-version but I couldn't see what requires that.  If you change it to run on 7.1, I can take another look.

So then ...
I copied your `AddNewCountryFormType` and controller to my test system and got it working. It works for me. When you add a new country (tag) the value comes through to the transformer as an array of strings prefixed by `__`. That's correct.

Then I looked at your page https://select2-demo.herokuapp.com/form/?formClass=App%5CForm%5CAddNewCountryFormType

Somehow it is not seeing the data attributes. Specifically `data-tags-text` and `data-new-tag-prefix` exist on the select tag but somehow is not seen by the Javascript. I don't know why.

You can observe the immediate problem simply by entering two characters. The resulting dropdown does not have `(NEW)` appended to it.

Again, if you can make you code work in PHP 7.1, I;ll take another look.

**Comment by tetranz** [comment]
@tacman I had a play with this. Unfortunately I was not able to reproduce the problem.

Firstly, I couldn't install your repo because it requires PHP 7.3. I should probably upgrade my test VM to 7.3 but I don't have time for that right now.  It's something to do with ocramius/package-version but I couldn't see what requires that.  If you change it to run on 7.1, I can take another look.

So then ...
I copied your `AddNewCountryFormType` and controller to my test system and got it working. It works for me. When you add a new country (tag) the value comes through to the transformer as an array of strings prefixed by `__`. That's correct.

Then I looked at your page https://select2-demo.herokuapp.com/form/?formClass=App%5CForm%5CAddNewCountryFormType

Somehow it is not seeing the data attributes. Specifically `data-tags-text` and `data-new-tag-prefix` exist on the select tag but somehow is not seen by the Javascript. I don't know why.

You can observe the immediate problem simply by entering two characters. The resulting dropdown does not have `(NEW)` appended to it.  The posted value does not have `__` prepended so therefore the transformer does not recognize the value is new so the code falls through to the SQL query which fails. If the `__` was there, the first loop in the transformer would remove it from the query.

Again, if you can make you code work in PHP 7.1, I'll take another look.

**Comment by tacman** [comment]
OK, I've removed doctrine/orm-pack, which got rid of migrations, which had a dependency that required php 7.3.  I think it will run now on 7.1

```bash
git clone git@github.com:survos/select2entity-bundle-demo.git sel2-demo && cd sel2-demo 
composer install
bin/console doctrine:schema:update --force && bin/console doctrine:fixtures:load -n
yarn install
yarn run encore dev
```

Thanks!

**Comment by tacman** [comment]
BTW, I locked select2.js at 4.0.5 because of the bug with the field losing focus on multiple selects.  I think that's been fixed in master, not sure if there's a release yet.  Not sure if that's related.

**Comment by tacman** [comment]
I've updated select2.js to 4.0.8 (the latest version), still having the
same issue on the demo.

**Comment by tetranz** [comment]
@tacman I got it working this time.

I think the main problem is that the code from select2entity.js is not being loaded. Unfortunately I'm not an expert at all on webpack etc. I need to learn more about that.

Maybe I'm missing it but I don't see where you tell it to load select2entity.js.

I realize that you're trying to do the correct thing and crunch it into app.js. I'd like to learn how to do that too and document it properly. I'm not sure if the package needs to be modified to make that possible.

That said, this is how I got it working.

In webpack.config.js I add this under the `.addEntry('app'` line.
```
.addEntry('tetranz', './vendor/tetranz/select2entity-bundle/Resources/public/js/select2entity.js')
```
Uncomment the `.autoProvidejQuery()` line.

In the base.html.twig add this:
```
{% block javascripts %}
  {{ parent() }}
  {{ encore_entry_script_tags('tetranz') }}
{% endblock %}
```
You don't need the `$('.js-select2').select2({});` you have in app.js and (I assume) the related `js-select2` class on the form element.

Then it should work. I know that's not the perfect answer but it illustrates the basic problem that the code is not being loaded. Your form etc is all okay although note that add new tag functionality only works with `multiple = false`.

Maybe someone else can give some advice here as to the correct way to do it.

![Screen Shot 2019-08-06 at 9 29 59 PM](https://user-images.githubusercontent.com/2892757/62587770-66719800-b891-11e9-9bfb-9c040ac843b7.png)

**Comment by tacman** [comment]
Thanks!  Yep, that works now.  I've updated the demo and documentation. So I was using the PHP part of this bundle to create the data attributes on the form elements, but then only calling the select2 javascript, which worked for the selection.

Thanks for your help in figuring this out!
