### ISSUE TITLE
Foreign Entity with invalid value causes sql error

### ISSUE THREAD

**Issue by miholeus** [tetranz/select2entity-bundle#25]
There is a bug with foreign entity.
I have a form ``Book``, that has field ``author_id``. Author id is taken from ``users.id``. 
If I submit integer values, then all is fine. But when I submit text instead of integer id, I get doctrine exception
``
Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.firstname AS firstname_2 FROM users t0 WHERE t0.id = ?' with params ["test"]
``

The default Symfony Form Entity is working fine, it returns ``This value is not valid.`` error

**Comment by tetranz** [comment]
I'm not sure if I understand the problem. Does you author entity have a string or integer for its id?

I must admit that until tonight I've only tried it with entities with auto integer ids but I just created an entity with a string id and made it the "one" part of a many to one relationship like your author and book. That works fine for me.

Also, for an entity that uses an integer id, I changed my json query to return strings. i.e., the id values now have quotes around them which they don't with integers. That worked fine too as I would expect with PHP type conversion.

If your author has an integer id and your select query returns json that has string ids which do not convert to an integer then of course it will crash when the data transformer tries to ->find the entity. But ... maybe I'm misunderstanding the problem.

**Comment by miholeus** [comment]
Ok, I'll try to explain better. When a form is generated, you can look at html code at select tag, you'll see that option value has integer id. Try to modify that value to string and submit the form, you'll see SQL error. So in my case instead of user id I submit some mess string and it crashes. The default symfony component correctly handles this issue and you get ``This value is not valid.``

**Comment by tetranz** [comment]
I see what you mean now. I agree, it should give a better error message. I'll take a look at it in the next few days. I guess it needs a try / catch around the ->find in the data transformer to catch the doctrine error and then throw something similar to the standard component.

**Comment by tetranz** [comment]
I think this is fixed. Try dev-master now. If it looks good then I'll tag version 2.51.

It just needed to throw the correct exception in the data transformer. It now catches Doctrine's DriverException and throws Symfony form's TransformationFailedException. The form catches that and displays "This value is not valid.".

It's not perfect for a multiple value select because the transformer does one query for all selected entities. One bad id of the wrong type makes the whole query fail. You still end up back on the form with "This value is not valid." but the select blocks show ids rather than text. I don't think there is a solution for that other than perhaps querying each entity individually but that seems a little excessive. It's better than what it was doing before.

**Comment by miholeus** [comment]
Yes, it's working great now. Thank you!

**Comment by tetranz** [comment]
Thanks. I released version 2.51.
