### ISSUE TITLE
Wrong tags for composer

### ISSUE THREAD

**Issue by martijnhartlief** [tetranz/select2entity-bundle#47]
When trying to update to 2.8 its get overwritten by 2.52 because 52>8
Perhaps you can remove the tags and retag as 2.5.2 and 2.5.1 ?

**Comment by tetranz** [comment]
Yeah, I guess I messed up the versioning. I did as you suggested and retagged the commits for 2.51 and 2.52 as 2.5.1 and 2.5.2 then I deleted the old tags and releases. Hopefully nobody was using 2.51 an 2.52 specifically. I'm not sure why Packagist is still showing 2.52. Maybe it just hasn't caught up yet.
 I'll stick with semantic versioning from now on.

**Comment by martijnhartlief** [comment]
Yeah it still wants to install 2.52, so packagist needs to be informed/changed as well.

**Comment by tetranz** [comment]
I think it's good now. I logged into Packagist and deleted 2.52. I don't know why I had to do that because the 2.51 and 2.52 tag no longer exist on GitHub and 2.51 disappeared from Packagist automatically.
![screenshot from 2016-09-12 06-50-03](https://cloud.githubusercontent.com/assets/2892757/18433385/41d2d28a-78b5-11e6-9c41-4e40a4a42e21.png)
