### ISSUE TITLE
Not working with functional tests

### ISSUE THREAD

**Issue by binarious** [tetranz/select2entity-bundle#49]
I'd like to run functional tests and submit a form with this field, but I get the following error:

```
InvalidArgumentException: Input "my_select2_field" cannot take "1" as a value (possible values: ).
```

Any ideas?

**Comment by binarious** [comment]
@tetranz Do you have a workaround for this?

**Comment by tetranz** [comment]
What http request are you sending to get that exception? Maybe I'm misunderstanding but the only place in Symfony where I can find the text "possible values" is related to the choice field but I don't think this field extends the choice field.

**Comment by binarious** [comment]
Thank you for responding.

This is my field:
```php
->add('receiver', 'tetranz_select2entity', [
    'multiple' => true,
    'remote_route' => 'mail_search_receiver',
    'class' => 'AppBundle\Entity\User',
    'text_property' => 'email',
    'minimum_input_length' => 2,
    'page_limit' => 10,
    'language' => 'de',
    'placeholder' => 'Wählen Sie Empfänger',
    'constraints' => [
        new \Symfony\Component\Validator\Constraints\NotNull(),
        new \Symfony\Component\Validator\Constraints\NotBlank()
    ]
])
```

And this is my test:
```php
$form = $crawler->selectButton('E-Mail(s) senden')->form([
    'email_write[receiver]' => ['1'], // line 58
    'email_write[sender]' => 'mail@myvendor.de',
    'email_write[subject]' => 'Betreff'
]);
$crawler = $client->submit($form);
```

The error:
```
1) AppBundle\Tests\Controller\EmailControllerTest::testWrite
InvalidArgumentException: Input "email_write[receiver]" cannot take "1" as a value (possible values: ).

/Users/myuser/projects/myapp/vendor/symfony/symfony/src/Symfony/Component/DomCrawler/Field/ChoiceFormField.php:136
/Users/myuser/projects/myapp/vendor/symfony/symfony/src/Symfony/Component/DomCrawler/FormFieldRegistry.php:124
/Users/myuser/projects/myapp/vendor/symfony/symfony/src/Symfony/Component/DomCrawler/Form.php:77
/Users/myuser/projects/myapp/vendor/symfony/symfony/src/Symfony/Component/DomCrawler/Crawler.php:764
/Users/myuser/projects/myapp/src/AppBundle/Tests/Controller/EmailControllerTest.php:58
```

**Comment by tetranz** [comment]
I've had a play with this and I can produce the same error but I'm not sure if it's a bug or just the way the crawler works.

I'm not very familiar with it but I think when you do `$crawler->selectButton('E-Mail(s) senden')->form()` the crawler finds that button in the response and returns a representation of the form which contains that button. It only recognizes real html form elements. It doesn't know anything about the Javascript capability of select2. In our case it finds the `<select>` and its containing `<option>` tags. The crawler will not allow you to submit a value which is not one of its `<options>`.

Since your `possible values: ` is blank, I assume you're trying this on a form with no existing values in `receiver`. My field is called called members, not receiver, but I get the same result. If I set it so that the form is retrieved with several existing values, my error message then says something like:

`Input "team[members]" cannot take "1" as a value (possible values: 748, 876)`

748 and 876 are the existing values and therefore the `<option>` tags.

I think it is working as expected.

**Comment by binarious** [comment]
Well, I don't want to set possible values, because I chose the `remote_route` option to load the values via ajax since adding hundreds of thousands of options would be a performance killer. As a workaround I could replace this with predefined values when the app is in the test env, but it would be better to provide a solution directly in this bundle. Maybe to load all elements in possible values when using `remote_route` and when running inside a test.

**Comment by rosskea** [comment]
I don't think it makes sense to try to "fix" this in the bundle. It would be wrong for something to change its behavior only if it detects that it is being tested. That would defeat the purpose of the test.  Even if we tried to do that and load all possible elements, what happens if there are a million possible values?

I think the fundamental issue here is that if you want to do functional tests on a component that requires Javascript then your testing tool needs to do Javascript.

**Comment by tetranz** [comment]
I don't think it makes sense to try to "fix" this in the bundle. It would be wrong for something to change its behavior only if it detects that it is being tested. That would defeat the purpose of the test.  Even if we tried to do that and load all possible elements, what happens if there are a million possible values?

I think the fundamental issue here is that if you want to do functional tests on a component that requires Javascript then your testing tool needs to do Javascript.

**Comment by binarious** [comment]
> Even if we tried to do that and load all possible elements, what happens if there are a million possible values?

It's up to the person writing the test to produce a usable amount of test data.

> It would be wrong for something to change its behavior only if it detects that it is being tested.

The problem is that functional tests are breaking when using this bundle. I find it even more problematic to remove it just to be able to run a test, but I get your point.

Fell free to close the issue if you still think it's not worth adding a solution.

**Comment by tetranz** [comment]
I'm happy to leave this open for a while to see if anyone else has any comment or ideas.

It's not that I don't think it's worth adding a solution, it's more that I don't see how a solution is possible in any remotely sensible or realistic way. 

How do you suggest we do this?

To detect when a test is happening, we'd have to look at the http request and make a decision based on the user-agent string or maybe a special URL parameter or something. It would have to be done on the initial GET. If it determined that it was being tested it would then somehow have to pass that knowledge to the remote_route so that whatever query etc returns the data could do something special return all possible data values hoping that will not be an excessive amount of data.

Then we would end up with a `<select>` with an `<option>` for every possible value so the crawler will be happy to send any of those values.

Of course anyone else could craft such a query and pretend to be the Symfony crawler potentially causing problems.

Any of those steps would be a huge violation of good practice.

**Comment by binarious** [comment]
> To detect when a test is happening, we'd have to look at the http request and make a decision based on the user-agent string or maybe a special URL parameter or something.

Isn't it possible for a bundle to check the current environment? 

> If it determined that it was being tested it would then somehow have to pass that knowledge to the remote_route

Yes, that's true if you use a remote service outside of the application's scope. I'd say that the tester has to mock the remote service in this case somehow. When it's a remote url of the symfony application, then it's also aware of the environment being `'test'`.

> Of course anyone else could craft such a query and pretend to be the Symfony crawler potentially causing problems.

This wouldn't be a problem when checking the current symfony environment.

**Comment by tetranz** [comment]
Yes, you're correct, of course, about checking the environment. I haven't done much with environments.

We've been talking about `remote_route` but, now that I think more about it, that's not really relevant. The `transform` method of the transformer needs to do something different in the test environment.

We already have the ability to use a custom transformer so it would be very easy to supply a "test" transformer which returns some test data from its `transform` method. That would cause `<option>` tags to be rendered and therefore the test would pass if the crawler POSTed one of the test values. Do we need anything more? I guess we could have a `test_transformer` config setting that only gets used in the test environment or, more generally, have some sort of `environment` setting related to the `transformer` setting we have now.

I still feel that the goal is kind of wrong here. This will make the test "pass" but it's not really useful because the crawler sees this as a standard `<select>` tag. We're just avoiding an ugly but mostly meaningless test failure.

I think this whole issue is related more to the fact that we don't have a graceful fallback for a request that doesn't support JavaScript. I guess that's more of a select2 thing.

**Comment by binarious** [comment]
> We already have the ability to use a custom transformer so it would be very easy to supply a "test" transformer which returns some test data from its transform method. That would cause <option> tags to be rendered and therefore the test would pass if the crawler POSTed one of the test values. Do we need anything more?

That sounds great. So this is already implemented, right? Is there any documentation about it?

> We're just avoiding an ugly but mostly meaningless test failure.

It just makes functional tests of forms easier which use this bundle.

**Comment by tetranz** [comment]
There's no real documentation other than the `transformer` option which should be the fully qualified class name of a custom transformer.  The Symfony documentation http://symfony.com/doc/current/form/data_transformers.html will tell you how transformers work but basically you could write override the `transform` method to detect test mode and return whatever values you want. That should make the test tool happy when it tries to POST one of those values.

**Comment by binarious** [comment]
Thank you.

**Comment by ryancastle** [comment]
Very rudimentary work-around using the form theme...

        <select {{ block('widget_attributes') }}>
            {# In 'test' env we POST IDs and the DomCrawler needs to see an <option> node #}
            {% if app.environment == 'test' %}
                {% for value in range(1,100) %}
                    <option value="{{ value }}"></option>
                {% endfor %}
            {% endif %}

            {% if value is iterable %}
                {% for id, label in value %}
                    {% block tetranz_select2entity_widget_select_option %}
                        <option value="{{ id }}" selected="selected">{{ label }}</option>
                    {% endblock %}
                {% endfor %}
            {% endif %}
        </select>

**Comment by michael-joyce** [comment]
I worked around this by disabling the validation on the inputs like this 

```php
$form = $formCrawler->selectButton('Save')->form([
    'province[label]' => 'New Label',
    'province[description]' => 'New Description',
]);
$form['province[nation]']->disableValidation()->setValue(1);
```

It would be convenient to set the nation with the other form values, but this works fine.
